build:
  image: geppettoapps/crystal-libxml2:$$CRYSTAL_VERSION
  commands:
    - crystal deps
    - crystal tool format --check src spec
    - crystal spec
cache:
  mount:
    - .shards
matrix:
  CRYSTAL_VERSION:
    - 0.18.7
    - 0.19.0
    - 0.19.1
